# -*- coding: utf-8 -*-
"""Complementing A Strand of DNA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CyYQ8cRsrO5DBdaENeqpgRekqMyznXbH

In DNA strings, symbols 'A' and 'T' are complements of each other, as are 'C' and 'G'.

The reverse complement of a DNA string s
 is the string sc
 formed by reversing the symbols of s
, then taking the complement of each symbol (e.g., the reverse complement of "GTCA" is "TGAC").

Given: A DNA string s
 of length at most 1000 bp.

Return: The reverse complement sc
 of s.
"""

#Start with a sequence of DNA, flip the sequence, and find the complement of each nucleotide
#The way we'll match each nucleotide to its complement is by creating a dictionary
dna_dict = {'A':'T', 'T':'A', 'G':'C', 'C':'G'}
def reverse_complement(dna):
  reverse= dna[::-1]
  reverse_complement = ''
  for nucleotide in reverse:
    reverse_complement += dna_dict[nucleotide]
  return reverse_complement

reverse_complement('AAAACCCGGT')