# -*- coding: utf-8 -*-
"""Counting Point Mutations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NErxeIxmoWoOw6A_KWeMaYi953C1zUuW

Problem

Figure 2. The Hamming distance between these two strings is 7. Mismatched symbols are colored red.
Given two strings s
 and t
 of equal length, the Hamming distance between s
 and t
, denoted dH(s,t)
, is the number of corresponding symbols that differ in s
 and t
. See Figure 2.

Given: Two DNA strings s
 and t
 of equal length (not exceeding 1 kbp).

Return: The Hamming distance dH(s,t).
"""

#First we check to make sure our two sequences are equal in length. Once that is true, we will count the number of times that there is a mismatch between the two sequences. We will do that by using a for loop and go through each nucleotide of our first sequence and make sure it matches at the same index at the second sequence.

seq_test1 = "atgatg"
seq_test2 ="ttgatg"

def hamming_distance(seq1, seq2):
  if len(seq1) != len(seq2):
    return "Sequences are not the same length"
  else:
    count = 0
    for position in range(len(seq1)):
      if seq1[position] != seq2[position]:
        count += 1
    return f"Hamming distance (number of mismatches): {count}"

hamming_distance('GAGCCTACTAACGGGAT','CATCGTAATGACGGCCT')