# -*- coding: utf-8 -*-
"""DNAtoRNA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H_0pTeTB4WT08_t1HcwdlbzC8c6KCuAk

RNA
"""

#GATGGAACTTGACTACGTAAATT

"""The following code intakes a DNA sequence as an input and will return its complementary RNA sequence"""

def DNA_to_RNA(sequence):
  RNA_Dictionary = {"A":"A", "G":"G", "C":"C", "T":"U"}
  return "".join(RNA_Dictionary[nucleotide] for nucleotide in sequence) #start with an empty string and for every nucleotide in our input sequence match with its value from our RNA dictionary and join that into our empty string

DNA_to_RNA ("GATGGAACTTGACTACGTAAATT")