# -*- coding: utf-8 -*-
"""GC Content

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bvTL9h95fZhtSVJQPsSWxnnGTzt4oZYd

Problem
The GC-content of a DNA string is given by the percentage of symbols in the string that are 'C' or 'G'. For example, the GC-content of "AGCTATAG" is 37.5%. Note that the reverse complement of any DNA string has the same GC-content.

DNA strings must be labeled when they are consolidated into a database. A commonly used method of string labeling is called FASTA format. In this format, the string is introduced by a line that begins with '>', followed by some labeling information. Subsequent lines contain the string itself; the first line to begin with '>' indicates the label of the next string.

In Rosalind's implementation, a string in FASTA format will be labeled by the ID "Rosalind_xxxx", where "xxxx" denotes a four-digit code between 0000 and 9999.

Given: At most 10 DNA strings in FASTA format (of length at most 1 kbp each).

Return: The ID of the string having the highest GC-content, followed by the GC-content of that string. Rosalind allows for a default error of 0.001 in all decimal answers unless otherwise stated; please see the note on absolute error below.
"""

#In this function our input is going to be a list of DNA sequences, 10 max. And we can check that by doing length(list). After checking we'll do a for loop and go through each sequence in our list and compute the GC content for each string. We'll return the highest GC percentage.

def GC_content(list):
  if len(list) > 10:
    return 'there are more than 10 sequences'
  else :
    for sequence in list:
      gc_values_list = []

      G_count= sequence.count('G')
      C_count= sequence.count('C')
      GC_content= ((G_count+C_count)/len(sequence)) * 100

      gc_values_list.append(GC_content)

      max_index = gc_values_list.index(max(gc_values_list))

      dna_max_gc = list[max_index]
    return max(gc_values_list), dna_max_gc

test_list=['CCTGCGGAAGATCGGCACTAGAATAGCCAGAACCGTTTCTCTGAGGCTTCCGGCCTTCCCTCCCACTAATAATTCTGAGG',
           'CCATCGGTAGCGCATCCTTAGTCCAATTAAGTCCCTATCCAGGCGCTCCGCCGAAGGTCTATATCCATTTGTCAGCAGACACGC']

GC_content(test_list)