# -*- coding: utf-8 -*-
"""Rosalind Solutions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uLUzuF0LU0yMFigl1nuzjEl7HfRHeJU5

This script will be used to count the number of nucleotides in an input DNA sequence
"""

#AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC

import pandas as pd
import numpy as np

#The .count function will return us the number of times each particular nucleotide appears
def count_nucleotides(sequence):
  A_count = sequence.count("A")
  C_count = sequence.count("C")
  G_count = sequence.count("G")
  T_count = sequence.count("T")

  return f"This is the number of times A appears: {A_count}, This is the numer of times C appears: {C_count}, This is the number of times G appears: {G_count}, This is the number of times T appears: {T_count}"

count_nucleotides("AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC")